#For swarm version 3.0 shuld be used
version: '2.0'

services:   
    front: 
        image: httpd:2.4
        ports: 
            - "8080:80"
        networks: 
            - backend
        #Bindmounting the html files is more practical when it comes to changes.
        volumes: 
            - ./httpd:/usr/local/apache2/htdocs/
        
    mydb:
        image: manavellam/mydb:v1.0
        environment: 
            MYSQL_ROOT_PASSWORD: root
        expose:
            - "3306"
        networks:
            - backend
        restart: always

    myapp:
        #Building is possible in compose, but not in Swarm
        #build: 
        #   context: .
        image: manavellam/myapp:v1.0
        ports: 
            - "8085:8085"
        depends_on:
            - mydb
        networks:
            - backend
        restart: always
#All containers communicate through this network
networks: 
    backend: