apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cheddar
  name: cheddar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheddar
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cheddar
    spec:
      containers:
      - image: errm/cheese:cheddar
        name: cheese
        resources: {}
status: {}
